---
title: "Furtos e Roubos SP"
author: "Vinicius Oike"
date: "12/31/2021"
output: html_document
---

```{r}

# 0. Preamble -------------------------------------------------------------
library(ghibli)
library(tidyverse)
library(showtext)
library(here)
library(imputeTS)
library(patchwork)

showtext_opts(dpi = 300)
showtext_auto()

font_add("Helvetica", "Helvetica.ttc")

colors <- ghibli_palettes$TotoroMedium

theme_vini <- theme_minimal() +
  theme(
    legend.position = "bottom",
    
    text = element_text(family = "Helvetica", size = 8),
    plot.title = element_text(size = 10),
    axis.text.x = element_text(angle = 90),
    
    panel.grid.minor.y = element_blank(),
    panel.grid.minor.x = element_blank(),
    
    panel.background = element_rect(fill = "white", colour = NULL),
    plot.background = element_rect(fill = "white", colour = NULL)
  )
```


```{r}
# 1. Data -----------------------------------------------------------------

pop <- read_csv2(here("data/2021_12/seade_populacao_municipio.csv"),
                 locale = locale(encoding = "UTF-8"))

pop <- pop %>%
  filter(cod_ibge == 3550308) %>%
  select(ano, populacao)


data <- read_csv(here("data/2021_12/ssp_sao_paulo.csv"))

data <- data %>%
  rename(
    total_roubo = total_de_roubo_outros
  ) %>%
  mutate(
    date = as.Date(paste(ano, mes, "01", sep = "-")),
    homicidio_culposo = homicidio_culposo_outros + homicidio_culposo_por_acidente_de_transito,
    total_furto = furto_de_veiculo + furto_outros,
    letalidade_violenta = homicidio_doloso + latrocinio + lesao_corporal_seguida_de_morte
  ) %>%
  left_join(pop, by = "ano") %>%
  arrange(date)

taxa <- data %>%
  mutate(ano = as.character(ano),
         mes = as.character(mes)) %>%
  mutate(across(where(is.numeric), ~ .x / populacao * 10^5))

series <- taxa %>%
  select(date, contains("furto"), contains("roubo")) %>%
  pivot_longer(cols = -date)

series_imputed <- parallel::mclapply(split(series, series$name), function(df) {
  
  # Extract series as numeric vector and convert to ts
  
  first_date <- min(df$date)
  first_mes <- lubridate::month(first_date)
  first_ano <- lubridate::year(first_date)
  
  y <- ts(df$value, start = c(first_ano, first_mes), frequency = 12)
  
  # Impute missing values using kalman filter
  imp <- imputeTS::na_kalman(y, model = "StructTS")
  # Estimate STL model and extract trend
  model.stl <- forecast::mstl(imp)
  trend.stl <- forecast::trendcycle(model.stl)
  
  # Try using X-13 ARIMA to evaluate seasonality
  model.seas <- try(seasonal::seas(imp))
  # If sucessful, extract trend, if not reuse series
  if (class(model.seas) == "try-error") {
    deseas <- imp
  } else {
    deseas <- forecast::seasadj(model.seas)
  }
  
  # Tidy output into single data.frame
  out <- data.frame(
    date = df$date,
    value = df$value,
    imputed = as.numeric(imp),
    trend = trend.stl,
    seas = as.numeric(deseas)
  )
})
# Rowbind all series
xseries <- bind_rows(series_imputed, .id = "name")

df_aux <- xseries %>%
  filter(name %in% c("total_furto", "total_roubo")) %>%
  select(date, name, trend, imputed)

# Aggregate by year
aseries <- xseries %>%
  mutate(year = lubridate::year(date)) %>%
  group_by(name, year) %>%
  summarise(total_ano = mean(seas, na.rm = T)) %>%
  ungroup() %>%
  mutate(
    name_label = factor(
      name,
      labels = c("Furto Veiculo", "Furto Outros", "Roubo a Banco",
                 "Roubo de Carga", "Roubo de Veiculo",
                 "Roubo Outros", "Furto Total", "Roubo Total")
    )
  )
```

```{r}
p1 <- ggplot() +
  geom_line(data = filter(df_aux, name == "total_furto"),
            aes(x = date, y = imputed),
            colour = colors[1]) +
  geom_line(data = filter(df_aux, name == "total_furto"),
            aes(x = date, y = trend),
            colour = colors[6], size = 1) +
  labs(
    x = NULL,
    y = "Casos (100.000 hab.)",
    title = "Taxa de Furtos",
    subtitle = "Taxa de furtos mensal em São Paulo. Linha sobreposta com tendência.",
    caption = "Fonte: Secretaria de Segurança Pública (SSP-SP)"
  ) +
  scale_y_continuous(
    breaks = seq(80, 220, 20),
    labels = format(seq(80, 220, 20), big.mark = ".")
  ) +
  scale_x_date(
    date_breaks = "1 year",
    date_labels = "%Y"
  ) +
  theme_vini

p2 <- ggplot(data = filter(df_aux, name == "total_roubo"),
       aes(x = date)) +
  geom_line(aes(y = imputed),
            colour = colors[1]) +
  geom_line(aes(y = trend),
            colour = colors[6], size = 1) +
  labs(
    x = NULL,
    y = "Casos (100.000 hab.)",
    title = "Taxa de Roubos",
        subtitle = "Taxa de roubos mensal em São Paulo. Linha sobreposta com tendência.",
    caption = "Fonte: Secretaria de Segurança Pública (SSP-SP). Dados anteriores a 2017 para Roubos Outros foram interpolados."
  ) +
  scale_y_continuous(
    breaks = seq(40, 140, 20),
    labels = format(seq(40, 140, 20), big.mark = ".")
  ) +
  scale_x_date(
    date_breaks = "1 year",
    date_labels = "%Y"
  ) +
  theme_vini

p3 <- ggplot(filter(aseries, str_detect(name, "furto")),
       aes(x = year, y = total_ano)) +
  geom_col(fill = colors[3]) +
  labs(title = "Furtos em SP",
       x = NULL,
       y = "Taxa Média por Mil Habitantes") +
  facet_wrap(~name_label) +
  theme_vini

p4 <- ggplot(filter(aseries, str_detect(name, "roubo"), year >= 2017),
       aes(x = year, y = total_ano)) +
  geom_col(fill = colors[3]) +
  labs(title = "Roubo em SP",
       x = NULL,
       y = "Taxa Média por Mil Habitantes") +
  facet_wrap(~name_label) +
  theme_vini

```

```{r}
panel <- p1 / p2
plots <- list(p1, p2, p3, p4)
for (i in seq_along(plots)) {
  
  name_file <- sprintf("roubos_furtos_sp_p%s.png", i)
  
  cowplot::save_plot(filename = here("graphics", "2021_12", name_file),
                     plot = plots[[i]])
  
}

cowplot::save_plot(filename = here("graphics/2021_12/roubos_furtos_panel.png"),
                   plot = panel
                   )
```

